name: GitHub Actions Demo
on: [push]
jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm install
      - name: Cypress tests
        uses: cypress-io/github-action@v2
