name: GitHub Actions Demo
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: client
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: server
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./
          start: "npm start --prefix server"
          wait-on: "http://localhost:8000"
